# Site settings
title: MoneyBin - One Stop Banking Service
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://moneybin.deploytech.me" # the base hostname & protocol for your site

# User setting
owner: MoneyBin
email:
facebook_username: MoneyBin-1932655916960155
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
